# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 03:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pulished_data',
            new_name='pulished_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='create_data',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_data',
        ),
        migrations.AddField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 3, 1, 51, 452680, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 3, 1, 51, 451674, tzinfo=utc)),
        ),
    ]
