# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 03:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0020_auto_20180515_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 3, 29, 51, 568949, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 3, 29, 51, 567947, tzinfo=utc)),
        ),
    ]
